fallenstardust/YGOMobile-cn-ko-en

- Classes/gframe/replay_mode.cpp
- Classes/gframe/single_duel.cpp
- Classes/gframe/single_mode.cpp
- Classes/gframe/tag_duel.cpp
now it works fine with the latest script reader change
> update script reader

- Classes/gframe/client_field.cpp
- Classes/gframe/event_handler.cpp
https://github.com/Fluorohydride/ygopro/pull/2130/files
> update card cover in oppo

- Classes/gframe/image_manager.cpp
- Classes/gframe/image_manager.h
now it can support any size of card images, rather than 177*254 only.
> support large pics

- mobile/src/main/java/cn/garymb/ygomobile/ui/home/MainActivity.java
- mobile/src/main/java/cn/garymb/ygomobile/ui/preference/fragments/SettingFragment.java
- mobile/src/main/res/values-zh/strings.xml
- mobile/src/main/res/values/strings.xml
修复始终弹出申请权限的问题
修复选中决斗助手选项时不检查权限的问题
修复提示文本
> fix DuelAssiatant tip

- mobile/src/main/java/cn/garymb/ygomobile/loader/CardLoader.java
- mobile/src/main/java/cn/garymb/ygomobile/loader/CardSearchInfo.java
- mobile/src/main/java/ocgcore/StringManager.java
ignore case
archtype name as keyword
> update search card

- mobile/assets_ko/data/conf/strings.conf
- mobile/src/main/res/values-ko/strings.xml
Re-Update | 2022-07-30
________________________________
strings.conf
strings.xml
> Re-Update Korean File

- mobile/assets_ko/data/conf/strings.conf
add setname | p.m. 20:40 South Korea
!setname 0x18a 고타이(Ghoti)
> add SR13+POTE-EN

- mobile/assets_ko/data/conf/strings.conf
!setname 0x18b R-ACE(레스큐 에이스)
!setname 0x18c 퓨어리
!setname 0x18d 어무(미캉코)
> add DBAD, update ot

- mobile/src/main/res/values-ko/strings.xml
Before : "새 업그레이드 버전을 찾아 다운로드하시겠습니까?"
After : "업그레이드할 새 버전을 찾았습니다. 다운로드하시겠습니까?"
> Update ko strings.xml

- mobile/assets/kor/data/conf/strings.conf
- mobile/src/main/res/values-ko/strings.xml
2022/12/02 | South Korea | a.m. 10:56
> fix strings.conf

- mobile/build.gradle
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/cn/garymb/ygomobile/ex_card/ExCard.java
- mobile/src/main/java/cn/garymb/ygomobile/ex_card/ExCardActivity.java
- mobile/src/main/java/cn/garymb/ygomobile/ex_card/ExCardListAdapter.java
- mobile/src/main/java/cn/garymb/ygomobile/ui/home/HomeFragment.java
- mobile/src/main/res/layout/activity_ex_card.xml
- mobile/src/main/res/layout/item_ex_card.xml
- mobile/src/main/res/values-ko/strings.xml
- mobile/src/main/res/values-zh/strings.xml
- mobile/src/main/res/values/strings.xml
使用Jsoup库解析html页面，添加了ExCardActivity，当解析成功时打开ExCardActivity，当解析失败时使用旧WebActivity。在strings.xml中添加了新字符串（韩语字符串使用机器翻译生成）
> add webcrawler to show ex-card

- mobile/src/main/res/values-ko/strings.xml
before : change the game data language
after : 게임 데이터 언어를 변경합니다.
> fix ko strings.xml

- mobile/src/main/java/cn/garymb/ygomobile/ui/home/HomeFragment.java
> new UI for webcrawler

- mobile/assets/kor/data/conf/strings.conf
> Update strings.conf | ko-KR

- mobile/assets/kor/data/conf/bot.conf
- mobile/assets/kor/data/conf/strings.conf
-bot.conf
-strings.conf
2023.10.25 AM 07:30 South Korea
> Translate to Korean

- mobile/assets/data/windbot/windbot/Dialogs/BA.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/VI-1911.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/Zefra.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/anothercopy.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/cirno.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/copy.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/default.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/ecclesia.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/gugugu.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/kiwi.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/kor.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/mokey.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/near.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/smart.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/soul.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/swordsman.es-ES.json
- mobile/assets/data/windbot/windbot/Dialogs/verre.es-ES.json
All dialogues were translated into Spanish
> Dialogues translated into Spanish

- mobile/assets/es/serverlist.xml
> Actualizar serverlist.xml

- mobile/assets/es/data/conf/strings.conf
- mobile/src/main/res/values-es/strings.xml
!setname 0x119d Horus el Dragón de la Llama Negra
> !setname 0x119d Horus el Dragón de la Llama Negra

- mobile/assets/kor/data/conf/bot.conf
- mobile/assets/kor/data/conf/strings.conf
> Update bot.conf and strings.conf

- mobile/src/main/java/cn/garymb/ygomobile/ui/cards/deck/DeckAdapater.java
修正了unSort不会随机打乱并导致60卡组倒数第二张牌固定的bug
> fix: use random shuffle for unSort

- mobile/src/main/java/cn/garymb/ygomobile/AppsSettings.java
- mobile/src/main/java/cn/garymb/ygomobile/Constants.java
- mobile/src/main/java/cn/garymb/ygomobile/loader/CardKeyWord.java
- mobile/src/main/java/cn/garymb/ygomobile/ui/settings/SettingFragment.java
- mobile/src/main/res/values-es/strings.xml
- mobile/src/main/res/values-jp/strings.xml
- mobile/src/main/res/values-ko/strings.xml
- mobile/src/main/res/values-zh/strings.xml
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preference_game.xml
因为不会朝鲜语、日语、西班牙语，所以这三个语种对应的<string>仍然是中文
学艺不精，代码写的不好，还请包涵
> 新增更改关键词的搜索分隔方式

- mobile/assets/kor/data/conf/strings.conf
I'm Teshiken1728 (Former: JSY1728)
I Updated strings.conf
> Update KR strings.conf
